### ISSUE TITLE
Handle situation when ParseCompilerVersion return None

### ISSUE THREAD

**Issue by tallero** [roc-streaming/roc-toolkit#479] opened 2022-09-19 17:14 UTC
The function `ParseCompilerVersion` in `site_scons/site_tools/roc/parsers.py` should never return None or the corresponding code in `/SConstruct` should be adapted to take that into consideration.

**Comment by gavv** [comment] 2022-12-22 15:41
Hi, thanks for report.

Do you have specific use case when this problem arises?

**Comment by tallero** [comment] 2023-01-11 19:52
I remember this problem arose while building the aur packages.

**Comment by gavv** [comment] 2023-03-07 13:41
I see.

We'll need to adjust SConstruct to handle the case when ParseCompilerVersion() was not able to detect compiler version. This is a valid case.

**Comment by gavv** [comment] 2023-03-07 16:02
Actually, I checked current scripts, and everywhere where we call ParseCompilerVersion, we check its return value and either report error or handle it some other way.

So most likely the issue is not relevant in 0.2.x, and I'm going to close it with "can't reproduce".

However feel free to reopen if you will experience it again or will be able to reproduce. Thanks.

**Closed by gavv** 2023-03-07 16:02 UTC
Labels: defect, build system
