### ISSUE TITLE
replace all `%` with `.format()` in python code

### ISSUE THREAD

**Issue by adrianopol** [roc-streaming/roc-toolkit#512] opened 2023-02-25 10:51 UTC
https://docs.python.org/2/library/stdtypes.html#str.format :
> format(*args, **kwargs)
> This method of string formatting is the new standard in Python 3, and should be preferred to the % formatting described in String Formatting Operations in new code.

**Comment by adrianopol** [comment] 2023-03-06 21:00
PRs:
- #513
- #517

**Comment by oliveselow87** [comment] 2023-05-13 03:55
@maximeborges

**Comment by oliveselow87** [comment] 2023-05-13 03:55
#537

**Comment by oliveselow87** [comment] 2023-05-13 03:56
#531

**Comment by oliveselow87** [comment] 2023-05-13 03:56
@jdeblese

**Comment by maximeborges** [comment] 2023-05-13 08:01
> @maximeborges  

Why are you pinging me there?
And what is the point of your four comments here?

**Comment by maximeborges** [comment] 2023-05-13 08:01
> @maximeborges  

Why are you pinging me there?
And what is the point of your four comments here?

**Comment by gavv** [comment] 2023-05-13 08:55
Seems this task really excites the minds

#534

**Comment by gavv** [comment] 2023-05-13 20:45
Landed

**Closed by gavv** 2023-05-13 20:45 UTC
Labels: build system, refactoring

**Comment by oliveselow87** [comment] 2023-05-14 03:19
Duplicate of #
<details><summary>Details</summary>
<p>



</p>
</details>
