### ISSUE TITLE
roc-recv  is hard to use

### ISSUE THREAD

**Issue by samsomlan** [roc-streaming/roc-toolkit#393] opened 2020-06-05 08:10 UTC
ubuntu 18.04,x86 64bit ,roc develop branch last version

1: sudo roc-recv -vvv -s rtp+rs8m::10001 -r rs8m::10002 --backup file:./test.wav
2: sudo roc-recv -vvv -s rtp+rs8m://127.0.0.1:10001 -r rs8m://127.0.0.1:10002 --backup file:./test.wav
all got the same error log
16:03:50.767 [6636] [dbg] roc_peer: pool: initializing: object_size=648 poison=0
16:03:50.767 [6636] [dbg] roc_peer: pool: initializing: object_size=2064 poison=0
16:03:50.767 [6636] [dbg] roc_peer: pool: initializing: object_size=4112 poison=0
16:03:50.767 [6637] [dbg] roc_netio: network loop: starting event loop
16:03:50.767 [6638] [dbg] roc_ctl: task queue: starting event loop
16:03:50.767 [6636] [dbg] roc_peer: context: initializing
16:03:50.767 [6636] [dbg] roc_sndio: initializing pulseaudio backend
16:03:50.767 [6636] [dbg] roc_sndio: initializing sox backend
16:03:50.767 [6636] [dbg] roc_sndio: pulseaudio sink: opening sink: device=(null)
16:03:50.767 [6636] [err] roc_sndio: pulseaudio sink: frame size is zero
16:03:50.767 [6636] [inf] roc_sndio: pulseaudio sink: closing sink
16:03:50.767 [6636] [err] roc_recv: can't open output file or device: uri=(null) format=(null)
16:03:50.768 [6636] [dbg] roc_peer: context: deinitializing

**Comment by gavv** [comment] 2020-06-05 08:19
Looks like a regression caused by #274. Current develop branch was not properly tested yet. I'll look at it tomorrow, thanks for reporting!

Note: `rtp+rs8m:://` - a typo, should be `rtp+rs8m://`.

Also, port `1` in `rs8m:://127.0.0.1:1` is probably a typo too.

**Comment by gavv** [comment] 2020-06-07 11:02
Should be fixed in fresh `develop`.

**Comment by gavv** [comment] 2020-07-08 14:50
Closing, feel free to reopen if necessary.

**Closed by gavv** 2020-07-08 14:50 UTC
Labels: defect, report
